// <auto-generated />
using System;
using System.Collections.Generic;
using Catalogue.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalogue.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251223163645_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Catalogue.Domain.Lookups.DeliveryMethods.DeliveryMethod", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(2)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("LU_DeliveryMethod", (string)null);
                });

            modelBuilder.Entity("Catalogue.Domain.Lookups.ManufacturerClassifications.ManufacturerClassification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .IsUnique()
                        .HasDatabaseName("uc_ManClass");

                    b.ToTable("LU_ManufacturerClassification", (string)null);
                });

            modelBuilder.Entity("Catalogue.Domain.Lookups.MediaTypes.MediaType", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("LU_MediaType", (string)null);
                });

            modelBuilder.Entity("Catalogue.Domain.Medias.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte>("TypeId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("Catalogue.Domain.Merchants.Merchant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("Active");

                    b.Property<string>("MerchantCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "Catalogue.Domain.Merchants.Merchant.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)");

                            b1.Property<string>("AddressLine3")
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)");

                            b1.Property<string>("AddressLine4")
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("County")
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "PostalCode", "Catalogue.Domain.Merchants.Merchant.Address#Address.PostalCode#PostalCode", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("CountryId")
                                        .IsRequired()
                                        .HasMaxLength(2)
                                        .HasColumnType("char(2)");

                                    b2.Property<string>("Postcode")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)");
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("MerchantCode")
                        .IsUnique();

                    b.ToTable("Merchant");
                });

            modelBuilder.Entity("Catalogue.Domain.ProductTypes.Entities.ProductSubType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductSubTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ProductSubTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ProductSubType");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ProductTypeID");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId", "ProductSubTypeName")
                        .IsUnique()
                        .HasDatabaseName("uc_SubType");

                    b.ToTable("ProductSubType");
                });

            modelBuilder.Entity("Catalogue.Domain.ProductTypes.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ProductTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ProductType");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeName")
                        .IsUnique()
                        .HasDatabaseName("uc_ProductType");

                    b.ToTable("ProductType");
                });

            modelBuilder.Entity("Catalogue.Domain.Products.Entities.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MerchantId")
                        .HasColumnType("int");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("StockLevel")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "GrossPrice", "Catalogue.Domain.Products.Entities.Offer.GrossPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("char(3)");

                            b1.Property<decimal>("Value")
                                .HasColumnType("money")
                                .HasColumnName("GrossPrice");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ProductCode");

                    b.ToTable("Offer");
                });

            modelBuilder.Entity("Catalogue.Domain.Products.Entities.ProductMedia", b =>
                {
                    b.Property<string>("ProductCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("MediaId")
                        .HasColumnType("int")
                        .HasColumnName("MediaID");

                    b.HasKey("ProductCode", "MediaId");

                    b.ToTable("ProductMedia");
                });

            modelBuilder.Entity("Catalogue.Domain.Products.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("ManufacturerClassificationId")
                        .HasColumnType("int")
                        .HasColumnName("ManufacturerClassificationID");

                    b.Property<int>("ProductSubTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ProductSubTypeID");

                    b.Property<string>("ProductTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ProductTypeID");

                    b.Property<byte>("TaxClass")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("_updatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("LastUpdated");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerClassificationId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Catalogue.Domain.WarehouseMerchants.WarehouseMerchant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("MerchantId")
                        .HasColumnType("int");

                    b.Property<int>("PreferenceOrder")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PreferenceOrder")
                        .IsUnique();

                    b.ToTable("WarehouseMerchant");
                });

            modelBuilder.Entity("Catalogue.Domain.Warehouses.Entities.WarehouseDeliveryMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CountryIsoCode")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<string>("DeliveryMethodId")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "GrossCost", "Catalogue.Domain.Warehouses.Entities.WarehouseDeliveryMethod.GrossCost#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("char(3)");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(5, 2)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "LeadTimes", "Catalogue.Domain.Warehouses.Entities.WarehouseDeliveryMethod.LeadTimes#WarehouseDeliveryLeadTime", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<byte>("MaximumLeadTime")
                                .HasColumnType("tinyint")
                                .HasColumnName("MaxLeadTime");

                            b1.Property<byte>("MinimumLeadTime")
                                .HasColumnType("tinyint")
                                .HasColumnName("MinLeadTime");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DeliveryMethodId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("WarehouseDeliveryMethod");
                });

            modelBuilder.Entity("Catalogue.Domain.Warehouses.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "Catalogue.Domain.Warehouses.Warehouse.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)");

                            b1.Property<string>("AddressLine3")
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)");

                            b1.Property<string>("AddressLine4")
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("County")
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "PostalCode", "Catalogue.Domain.Warehouses.Warehouse.Address#Address.PostalCode#PostalCode", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("CountryId")
                                        .IsRequired()
                                        .HasMaxLength(2)
                                        .HasColumnType("char(2)");

                                    b2.Property<string>("Postcode")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)");
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("WarehouseCode")
                        .IsUnique();

                    b.ToTable("Warehouse");
                });

            modelBuilder.Entity("Catalogue.Domain.Medias.Media", b =>
                {
                    b.HasOne("Catalogue.Domain.Lookups.MediaTypes.MediaType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK_SF_MS_MediaStorage_SF_MS_MediaType");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Catalogue.Domain.ProductTypes.Entities.ProductSubType", b =>
                {
                    b.HasOne("Catalogue.Domain.ProductTypes.ProductType", null)
                        .WithMany("ProductSubTypes")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalogue.Domain.Products.Entities.Offer", b =>
                {
                    b.HasOne("Catalogue.Domain.Products.Product", null)
                        .WithMany("Offers")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalogue.Domain.Products.Entities.ProductMedia", b =>
                {
                    b.HasOne("Catalogue.Domain.Products.Product", null)
                        .WithMany("ProductMedias")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalogue.Domain.Products.Product", b =>
                {
                    b.HasOne("Catalogue.Domain.Lookups.ManufacturerClassifications.ManufacturerClassification", "ManufacturerClassification")
                        .WithMany()
                        .HasForeignKey("ManufacturerClassificationId")
                        .IsRequired()
                        .HasConstraintName("FK_SF_Products_SF_LU_ManufacturerClassification");

                    b.Navigation("ManufacturerClassification");
                });

            modelBuilder.Entity("Catalogue.Domain.Warehouses.Entities.WarehouseDeliveryMethod", b =>
                {
                    b.HasOne("Catalogue.Domain.Lookups.DeliveryMethods.DeliveryMethod", "DeliveryMethod")
                        .WithMany()
                        .HasForeignKey("DeliveryMethodId")
                        .IsRequired()
                        .HasConstraintName("FK_DL_WarehouseDeliveryMethod_LU_DeliveryMethod");

                    b.HasOne("Catalogue.Domain.Warehouses.Warehouse", null)
                        .WithMany("WarehouseDeliveryMethods")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryMethod");
                });

            modelBuilder.Entity("Catalogue.Domain.ProductTypes.ProductType", b =>
                {
                    b.Navigation("ProductSubTypes");
                });

            modelBuilder.Entity("Catalogue.Domain.Products.Product", b =>
                {
                    b.Navigation("Offers");

                    b.Navigation("ProductMedias");
                });

            modelBuilder.Entity("Catalogue.Domain.Warehouses.Warehouse", b =>
                {
                    b.Navigation("WarehouseDeliveryMethods");
                });
#pragma warning restore 612, 618
        }
    }
}
