<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>014919d6-66d9-4a63-9394-9b1b30a848d9</UserSecretsId>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..</DockerfileContext>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.9" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.13.0" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.13.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.12.0" />
		<PackageReference Include="Scalar.AspNetCore" Version="2.11.0" />
		<PackageReference Include="Scalar.AspNetCore.Microsoft" Version="2.10.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\API.Models\API.Models.csproj" />
		<ProjectReference Include="..\API.Shared\API.Shared.csproj" />
		<ProjectReference Include="..\Catalogue.Application\Catalogue.Application.csproj" />
		<ProjectReference Include="..\Catalogue.Infrastructure\Catalogue.Infrastructure.csproj" />
	</ItemGroup>

</Project>
